steps:
# Install node package
- name: 'gcr.io/cloud-builders/npm:node-16.0.0'
  args: [ 'install' ]

# Build files
- name: 'gcr.io/cloud-builders/npm:node-16.0.0
  args: [ 'run', 'build', '--prod' ]

# Deploy to google cloud app engine.
- name: 'gcr.io/cloud-builders/gcloud'
  args: [ 'app', 'deploy', '--version=prod' ]
